modified:   vpnset

diff --git a/vpnset b/vpnset
--- a/vpnset
+++ b/vpnset
@@ -248,29 +248,10 @@ function root_prepare {
     /sbin/iptables-save > /etc/iptables/rules.v4
 
 
-    local DNSCRYPTSOCKET="/usr/lib/systemd/system/dnscrypt-proxy.socket"
-    if [ -f $DNSCRYPTSOCKET ]; then
-
-        echo "" >> $DNSCRYPTSOCKET
-        echo "[Socket]" >> $DNSCRYPTSOCKET
-        echo "ListenStream=127.0.0.1:53" >> $DNSCRYPTSOCKET
-        echo "ListenDatagram=127.0.0.1:53" >> $DNSCRYPTSOCKET
-        echo "" >> $DNSCRYPTSOCKET
-        echo "ListenStream=10.8.0.1:53" >> $DNSCRYPTSOCKET
-        echo "ListenDatagram=10.8.0.1:53" >> $DNSCRYPTSOCKET
-
-        systemctl daemon-reload ; systemctl restart dnscrypt-proxy.socket ; systemctl restart dnscrypt-proxy.service
-    fi
-
-
-    systemctl disable systemd-resolved
-    systemctl stop systemd-resolved
-
-
-    echo "" >> /etc/dhcp/dhclient.conf
-    echo "prepend domain-name-servers 127.0.0.1;" >> /etc/dhcp/dhclient.conf
-    dhclient -r && dhclient
-
+    
+    dnscrypt_proxy_configure
+    
+    
 }
 
 # ------------------------------------------------------------------------------
@@ -285,8 +266,8 @@ function dnscrypt_proxy_opt {
 
 
     pushd /opt/
-        wget https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.1.5/dnscrypt-proxy-linux_x86_64-2.1.5.tar.gz
-        tar xf dnscrypt-proxy-linux_x86_64-2.1.5.tar.gz --transform s/linux-x86_64/dnscrypt-proxy/
+        wget https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.1.15/dnscrypt-proxy-linux_x86_64-2.1.15.tar.gz
+        tar xf dnscrypt-proxy-linux_x86_64-2.1.15.tar.gz --transform s/linux-x86_64/dnscrypt-proxy/
     popd
 
     mkdir -p /etc/dnscrypt-proxy /var/log/dnscrypt-proxy
@@ -307,6 +288,45 @@ function dnscrypt_proxy_opt {
     systemctl daemon-reload ; systemctl restart dnscrypt-proxy.service
 
 }
+
+
+function dnscrypt_proxy_configure {
+    
+    notice "dnscrypt_proxy configure"
+
+    if ! whoami | grep -q root; then
+        err 'root required. exit.'
+    fi
+    
+    
+    local DNSCRYPTSOCKET="/usr/lib/systemd/system/dnscrypt-proxy.socket"
+    if [ -f $DNSCRYPTSOCKET ]; then
+
+        echo "" >> $DNSCRYPTSOCKET
+        echo "[Socket]" >> $DNSCRYPTSOCKET
+        echo "ListenStream=127.0.0.1:53" >> $DNSCRYPTSOCKET
+        echo "ListenDatagram=127.0.0.1:53" >> $DNSCRYPTSOCKET
+        echo "" >> $DNSCRYPTSOCKET
+        echo "ListenStream=10.8.0.1:53" >> $DNSCRYPTSOCKET
+        echo "ListenDatagram=10.8.0.1:53" >> $DNSCRYPTSOCKET
+
+        systemctl daemon-reload ; systemctl restart dnscrypt-proxy.socket ; systemctl restart dnscrypt-proxy.service
+    fi
+
+
+    systemctl disable systemd-resolved
+    systemctl stop systemd-resolved
+    
+    
+    local DHCLIENTCONF="/etc/dhcp/dhclient.conf"
+    if [ -f $DHCLIENTCONF ]; then
+        echo "" >> $DHCLIENTCONF
+        echo "prepend domain-name-servers 127.0.0.1;" >> $DHCLIENTCONF
+        dhclient -r && dhclient
+    fi
+    
+}
+
 
 # ------------------------------------------------------------------------------
 
